apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    component: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: stephengrider/multi-client
        ports:
        - containerPort: 3000
