# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redis-deployment
  namespace: default
  labels:
    component:  redis-deployment
spec:
  selector:
    matchLabels:
      component: redis
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        component:  redis
    spec:
      containers:
      - name:  redis
        image:  redis:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort:  6379
      restartPolicy: Always